version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    groups:
      dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"